### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by brihijoshi** [eujhwang/personalized-llms#4]
Hi!! Thanks for your work, I am trying to replicate a couple of things in the paper. 

I am unable to run the scripts as it's hard to find `data/topic_mapping.npy` file. Could I get a pointer of where that might be possibly?

Regards,
Brihi

**Comment by eujhwang** [comment]
Hello, you can find that file in the original opinion-qa repo: https://github.com/tatsu-lab/opinions_qa?tab=readme-ov-file

[OpinionQA dataset](https://worksheets.codalab.org/worksheets/0x6fb693719477478aac73fc07db333f69) > 	human_resp > topic_mapping.npy

**Comment by brihijoshi** [comment]
Thank you!!
